spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://aliyun-mysql.mysql.rds.aliyuncs.com/ssm_db?useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    username: lw0120
    password: Hao19980518

